---

- name: download nodejs repo
  get_url:
    url: https://rpm.nodesource.com/setup_8.x
    dest: /tmp/
    mode: 700
 
- name: install nodejs. repo
  shell: bash - setup_8.x
  args:
    chdir: /tmp/

- name: install node 8.x and npm 5.x
  yum: 
    name: nodejs
    state: latest
  
- name: install yarn
  npm:
    name: yarn
    global: yes
    path: /opt/

- name: git clone 
  git: 
    repo: https://github.com/weseek/growi.git
    dest: /opt/growi/

- name: yarn
  shell: yarn
  args:
    chdir: /opt/growi/

- name: Add Growi Service
  shell:
    cmd: |
      cat << 'EOF' | tee /etc/systemd/system/growi.service
      [Unit]
      Description=Growi
      After=network.target
      
      [Service]
      WorkingDirectory=/opt/growi
      EnvironmentFile=/etc/systemd/system/growi.conf
      ExecStart=/usr/bin/npm start

      [Install]
      WantedBy=multi-user.target
      EOF

- name: Add Growi Config
  shell:
    cmd: |
      cat << 'EOF' | tee  /etc/systemd/system/growi.conf
      PORT=3000
      MONGO_URI="mongodb://growi:password@localhost/growi"
      ELASTICSEARCH_URI="http://localhost:9200"
      EOF

- name: Growi Start and Enable
  systemd:
    name: growi
    daemon_reload: yes
    enabled: yes
    state: started
